// Note: Layout file...!

"use client";

import React, { FC } from "react";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import { RootLayoutProps } from "@/types/types";
import type { Metadata } from "next";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
  // console.log("Childrens: ", children);
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
};

export default RootLayout;